ansible-collections/community.digitalocean

- README.md
- galaxy.yml
Updates `README.md` and `galaxy.yml` to be relevant to current state of affairs.
Docs and Galaxy meta info.
See #1.
> Setup repository - README and galaxy.yml

- changelogs/fragments/14-docs-fqcn.yaml
- plugins/modules/digital_ocean.py
- plugins/modules/digital_ocean_sshkey_facts.py
- plugins/modules/digital_ocean_sshkey_info.py
> Fixes #14: Ensure all docs examples use FQCN.

- README.md
Fixes typo in README caused by human copy-paste error.﻿
> Fix copy-paste typo in README.

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/14-docs-fqcn.yaml
- galaxy.yml
- plugins/modules/digital_ocean_droplet.py
After merging and pushing a 1.0.0 tag, should close #11.﻿
> Issue #11: Add changelog, adjust README and galaxy.yml for 1.0.0 release.

- .github/workflows/ansible-test.yml
> Also run CI on pushes, and nightly

- README.md
Fix indentation of ordered list in `README.md`.
> Fix indentation of list in README.md

- plugins/modules/digital_ocean_domain.py
If the user do not give a IP for the @ record, we shouldn't
try to add 1.
Fix #21 
digital_ocean_domain
> Fix #21, make digital_ocean_domain idempotent

- changelogs/fragments/16-digitalocean-firewall.yaml
- plugins/modules/digital_ocean_firewall.py
This PR has the new module to create and update Digital Ocean Firewall rules.
digital_ocean_firewall
Related: https://github.com/ansible/ansible/pull/46618#issuecomment-671323757
> digital_ocean_firewall: new module

- changelogs/fragments/38-resize-volumes.yml
- plugins/modules/digital_ocean_block_storage.py
- tests/integration/targets/digital_ocean_block_storage/defaults/main.yml
- tests/integration/targets/digital_ocean_block_storage/tasks/main.yml
> 38-Add ability to resize Block Storage Volumes

- changelogs/fragments/33-add-domain-record.yaml
- plugins/modules/digital_ocean_domain_record.py
- plugins/modules/domain_record.py
Add a module to manage DO domain records, copied PR https://github.com/ansible/ansible/pull/31765/files, changing only lines noted from comments
Addresses https://github.com/ansible-collections/community.digitalocean/issues/6
`digital_ocean_domain_record`
> #6 Add Digital Ocean Domain Records

- changelogs/fragments/16-digitalocean-firewall.yaml
- changelogs/fragments/22-digital_ocean_domain-idempotent.yml
- changelogs/fragments/33-add-domain-record.yaml
- changelogs/fragments/38-resize-volumes.yml
- galaxy.yml
- plugins/modules/digital_ocean_domain_record.py
- plugins/modules/digital_ocean_firewall.py
Makes sure that for the current state of the collection:
1. New modules (and plugins) have a correct `version_added` entry. It **must** contain the version of the next minor/major collection release.
2. New modules (and plugins) must not have a changelog fragment. They are detected automatically by the changelog generator (that's why `version_added` is so important!). (Only jinja2 test and filter plugins must have a changelog fragment.)
3. All feature and bugfix PRs must have a changelog fragment.
4. All changelog fragments adhere to the precise format specified in https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to.
(See also https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)
- Docs Pull …
> Various changelog / new module fixes

- .github/workflows/ansible-test.yml
- tests/sanity/ignore-2.12.txt
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
> Testing against 2.11

- README.md
- plugins/modules/digital_ocean_balance_facts.py
- plugins/modules/digital_ocean_balance_info.py
New module for displaying customer balance.
* digital_ocean_balance_info
* digital_ocean_balance_facts
```paste below
❯ ansible-playbook -i localhost, -c local balance.yml -v
PLAY [localhost] **********************************************************************************************************************************************************
TASK [Balance information] ************************************************************************************************************************************************Sunday 11 April 2021  11:21:37 -0400 (0:00:00.050)       0:00:00.050 **********
ok: [localhost] => changed=false
ansible_facts:
discovered_interpreter_python: /usr/bin/python3
data:
account_balance: '-27.52'
generated_at: '2021-04-11T05:08:24Z' …
```
> New module for customer balance

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- galaxy.yml
Creating `1.1.1` to fix the version in the `README.md`.
Fixes #63.
* digitalocean
> Creating 1.1.1

- .github/workflows/ansible-test-integration.yml
- .github/workflows/ansible-test-sanity.yml
- .github/workflows/ansible-test-unit.yml
- codecov.yml
* Enable Unit tests (with code coverage)
* Tidy up integration tests so only invoke ansible-test once (avoids missing test, and speeds up)
> Enable Unit tests

- .github/workflows/ansible-test-unit.yml
Run unit test on pull requests.
> Run unit tests on PR

- plugins/modules/digital_ocean_database.py
- plugins/modules/digital_ocean_database_info.py
- plugins/modules/digital_ocean_kubernetes.py
- plugins/modules/digital_ocean_kubernetes_info.py
- tests/integration/targets/digital_ocean_database/defaults/main.yml
- tests/integration/targets/digital_ocean_database/tasks/main.yml
- tests/integration/targets/digital_ocean_kubernetes/defaults/main.yml
- tests/integration/targets/digital_ocean_kubernetes/tasks/main.yml
Fixes #20 and #37.
* `digital_ocean_kubernetes`
* `digital_ocean_kubernetes_info`
* `digital_ocean_database`
* `digital_ocean_database_info`
> Add K8s and Database modules and tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/digital_ocean_database.py
- plugins/modules/digital_ocean_database_info.py
- plugins/modules/digital_ocean_kubernetes.py
- plugins/modules/digital_ocean_kubernetes_info.py
> creating release-1.3.0

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/80-update-readme-k8s-dbs.yaml
- changelogs/fragments/81-fix-document-link-digital-ocean-droplet-info.yml
- changelogs/fragments/82-fix-sshkey-info.yaml
- galaxy.yml
Releasing 1.4.0; updated README to fix #79 .
> Releasing 1.4.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/83-droplet-inactive.yaml
- galaxy.yml
Release 1.4.1; fixes #66 and #83.
> Release 1.4.1

- tests/integration/targets/digital_ocean_droplet/tasks/main.yml
Fixing the Droplet integration tests.
> Fix Droplet integration tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/68-fix-sshkey-traceback.yaml
- changelogs/fragments/88-droplet-integration-tests.yaml
- galaxy.yml
Creating 1.4.2; couple of bugfixes.
> Creating 1.4.2

- changelogs/fragments/94-fix-db-attribs.yaml
- plugins/modules/digital_ocean_database.py
This resolves the issue of various database attributes not being set appropriately (everything being set to version instead of the appropriate attribute)
Fixes #94 
`digital_ocean_database`
N/A
> Fix db attribs

- changelogs/fragments/100-fix-database-info.yaml
- plugins/modules/digital_ocean_database_info.py
This PR cleans up attribs that were unused and were being set incorrectly. It also removes the use of `state`, which is unnecessary in the info module.
`digital_ocean_database_inifo`
```paste below
```
> database_info cleanup

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/97-wire-up-inventory-cache.yml
- galaxy.yml
Creating 1.5.1; fixes dynamic inventory caching.
> Creating 1.5.1

- plugins/modules/digital_ocean_project.py
- tests/integration/targets/digital_ocean_project/tasks/main.yml
Begins to address #71 by adding the ability to manage a DO project
digital_ocean_project 
This adds the ability to manage a digital ocean project via this collection.
> Add project module

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/102-filters-prefixed-vars.yml
- changelogs/fragments/55-fix-info-module-return-type.yaml
- galaxy.yml
Creating 1.6.0; bugfixes and new modules 🎉
> Creating 1.6.0

- README.md
- changelogs/fragments/112-update-readme.yaml
We forgot to add the new project modules to the `README.md` in the last release.
* digital_ocean_project_info
* digital_ocean_project
> Add missing (new) modules to README.md

- changelogs/fragments/114-fix-integration-tests.yaml
- plugins/modules/digital_ocean_kubernetes.py
- tests/integration/targets/digital_ocean_certificate/tasks/main.yml
- tests/integration/targets/digital_ocean_firewall/tasks/main.yml
- tests/integration/targets/digital_ocean_kubernetes/defaults/main.yml
- tests/integration/targets/digital_ocean_tag/tasks/main.yml
Fixes #114; small bugfixes on these integration tests, minor change to Kubernetes (adding and defaulting to "latest" version).
* digital_ocean_certificate
* digital_ocean_firewall
* digital_ocean_tag
* digital_ocean_kubernetes
> Fix integration tests (certificate, firewall, tag, kubernetes)

- README.md
- plugins/modules/digital_ocean_vpc.py
- plugins/modules/digital_ocean_vpc_info.py
- tests/integration/targets/digital_ocean_vpc/defaults/main.yml
- tests/integration/targets/digital_ocean_vpc/tasks/main.yml
- tests/integration/targets/digital_ocean_vpc_info/tasks/main.yml
Fixes #69.
* digital_ocean_vpc_info
* digital_coean_vpc
```ansible
- name: Fetch all VPCs
community.digitalocean.digital_ocean_vpc_info:
oauth_token: "{{ do_api_key }}"
- name: Create a VPC
community.digitalocean.digital_ocean_vpc:
state: present
oauth_token: "{{ do_api_key }}"
name: "{{ vpc_name }}"
region: "{{ do_region }}"
- name: Delete a VPC
community.digitalocean.digital_ocean_vpc:
state: absent
oauth_token: "{{ do_api_key }}"
name: "{{ vpc_name }}"
- name: Fetch all VPCs
community.digitalocean.digital_ocean_vpc_info:
register: my_vpcs
- name: Fetch members of a VPC
community.digitalocean.digital_ocean_vpc_info:
members: true
name: myvpc1
register: my_vpc_members
```
> New module: DigitalOcean VPCs

- README.md
- plugins/modules/digital_ocean_snapshot.py
- tests/integration/targets/digital_ocean_snapshot/defaults/main.yml
- tests/integration/targets/digital_ocean_snapshot/tasks/main.yml
Fixes #91; create and delete Droplet and volume snapshots.
* digital_ocean_snapshot
```yaml
- name: Snapshot a Droplet
community.digitalocean.digital_ocean_snapshot:
state: present
snapshot_type: droplet
snapshot_name: mysnapshot1
droplet_id: 250329179
register: result
- name: Delete a Droplet snapshot
community.digitalocean.digital_ocean_snapshot:
state: absent
snapshot_type: droplet
snapshot_id: 85905825
register: result
- name: Snapshot a Volume
community.digitalocean.digital_ocean_snapshot:
state: present
snapshot_type: volume
snapshot_name: mysnapshot2
volume_id: 9db5e329-cc68-11eb-b027-0a58ac144f91
- name: Delete a Volume snapshot
community.digitalocean.digital_ocean_snapshot:
state: absent
snapshot_type: volume
snapshot_id: …
```
> New module: DigitalOcean Snapshot (Droplet and Volume)

- .github/workflows/ansible-test-integration.yml
- changelogs/fragments/121-integration-tests.yaml
- tests/integration/requirements.txt
Adding `community.general` and `jmespath` to integration tests; fixes #121.
* digital_ocean
> Integration: Tests need community.general and jmespath

- changelogs/124-add-mongodb.yaml
- plugins/modules/digital_ocean_database.py
Adding support for MongoDB in the database module; fixes #124.
* digital_ocean_database
> Database: Adding support for MongoDB

- changelogs/fragments/131-floating-ip-tests.yaml
- tests/integration/targets/digital_ocean_floating_ip/tasks/main.yml
- tests/integration/targets/digital_ocean_floating_ip_info/defaults/main.yml
- tests/integration/targets/digital_ocean_floating_ip_info/tasks/main.yml
Delete all Floating IPs initially (we're currently at the limit). Add a new test for the info module. I use the term "fixes" loosely for #128 (I don't know the root cause of this yet), but should fix #130.
* digital_ocean_floating_ip
* digital_ocean_floating_ip_info
> Integration Tests: Floating IPs (fix existing, add new info test)

- changelogs/fragments/134-database-tests.yaml
- tests/integration/targets/digital_ocean_database/defaults/main.yml
- tests/integration/targets/digital_ocean_database/tasks/main.yml
Fixes #134.
* digital_ocean_database
> Increase database creation wait to 900s

- changelogs/fragments/139-info-modules-check-mode.yaml
- plugins/modules/digital_ocean_account_info.py
- plugins/modules/digital_ocean_balance_info.py
- plugins/modules/digital_ocean_certificate_info.py
- plugins/modules/digital_ocean_database_info.py
- plugins/modules/digital_ocean_domain_info.py
- plugins/modules/digital_ocean_droplet_info.py
- plugins/modules/digital_ocean_firewall_info.py
- plugins/modules/digital_ocean_floating_ip_info.py
- plugins/modules/digital_ocean_image_info.py
- plugins/modules/digital_ocean_kubernetes_info.py
- plugins/modules/digital_ocean_load_balancer_info.py
- plugins/modules/digital_ocean_project_info.py
- plugins/modules/digital_ocean_region_info.py
- plugins/modules/digital_ocean_size_info.py
- plugins/modules/digital_ocean_snapshot_info.py
- plugins/modules/digital_ocean_tag_info.py
- plugins/modules/digital_ocean_volume_info.py
Fixes #139.
Bunch of info modules were missing this. Since info modules *shouldn't* actually do anything, I'm wondering if there's anything that actually needs implementation.
> Adding missing check mode to info modules

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/131-floating-ip-tests.yaml
- changelogs/fragments/134-database-tests.yaml
- changelogs/fragments/134-psf-black.yaml
- changelogs/fragments/138-group-name-transformations.yaml
- changelogs/fragments/139-info-modules-check-mode.yaml
- galaxy.yml
- tests/unit/plugins/inventory/test_digitalocean.py
Creating 1.9.0; minor changes and bugfixes.
> Creating 1.9.0

- changelogs/fragments/147-load-balancer-fixes.yaml
- plugins/modules/digital_ocean_load_balancer.py
- tests/integration/targets/digital_ocean_load_balancer/tasks/main.yml
After merging #145, I found some problems in the load balancer module and integration test. This should fix things, but, I've been noticing Droplet creation events in nyc1. We might want to switch to nyc3.
* digital_ocean_load_balancer
> Load balancer fixes

- changelogs/fragments/149-block-detach-not-idempotent.yaml
- plugins/modules/digital_ocean_block_storage.py
Fixes #149.
* digital_ocean_block_storage
> Fixing block volume detach idempotency

- README.md
- plugins/module_utils/digital_ocean.py
- plugins/modules/digital_ocean_cdn_endpoints.py
- plugins/modules/digital_ocean_cdn_endpoints_info.py
Fixes #155.
* digital_ocean_cdn_endpoints_info
* digital_ocean_cdn_endpoint
> RFE: CDN Endpoints module

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/143-droplet-resize-wait-active.yaml
- changelogs/fragments/147-load-balancer-fixes.yaml
- changelogs/fragments/149-block-detach-not-idempotent.yaml
- changelogs/fragments/150-droplet-active-power-on.yaml
- changelogs/fragments/157-doks-auto-scale.yaml
- galaxy.yml
Release 1.10.0; new modules, minor changes, bugfixes.
> Release 1.10.0

- README.md
- changelogs/fragments/164-add-badges.yaml
Adding (missing) badges for black and unit tests; we run these tests, might as well display them on the `README.md`.
* `README.md`
> Adding badges for black and unit tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/140-resize-state-active.yaml
- changelogs/fragments/159-add-droplet-firewall.yaml
- changelogs/fragments/170-add-flip-states.yaml
- changelogs/fragments/171-add-project-support.yaml
- changelogs/fragments/174-return-value-fix.yml
- changelogs/fragments/179-cdn-integration-tests.yaml
- changelogs/fragments/181-firewall-destroy-fix.yaml
- changelogs/fragments/186-tests-running-twice.yaml
- galaxy.yml
Release 1.12.0; lots of minor changes and bugfixes -- Happy Hacktoberfest 🎃 🎃 🎃
> Release 1.12.0

- changelogs/fragments/194-droplet-sleep-variable.yaml
- plugins/modules/digital_ocean_droplet.py
- tests/integration/targets/digital_ocean_droplet/tasks/main.yml
> Allow the user to override the polling interval

- .github/workflows/ansible-test-integration.yml
- .github/workflows/ansible-test-sanity.yml
- .github/workflows/ansible-test-unit.yml
- .github/workflows/pull-request-integration.yml
- changelogs/fragments/190-kubernetes-ha.yaml
- plugins/modules/digital_ocean_kubernetes.py
- plugins/modules/digital_ocean_kubernetes_info.py
- tests/integration/targets/digital_ocean_kubernetes/defaults/main.yml
- tests/integration/targets/digital_ocean_kubernetes/tasks/main.yml
- tests/integration/targets/digital_ocean_kubernetes_info/defaults/main.yml
- tests/integration/targets/digital_ocean_kubernetes_info/tasks/main.yml
- tests/unit/plugins/modules/test_digital_ocean_kubernetes.py
- tests/unit/plugins/modules/test_digital_ocean_kubernetes_info.py
Fixes #190.
* digital_ocean_kubernetes
> Adding support for K8s HA control plane

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/190-kubernetes-ha.yaml
- changelogs/fragments/194-droplet-sleep-variable.yaml
- galaxy.yml
Creating the 1.13.0 release; minor changes to the Droplet and Kubernetes modules.
> Release 1.13.0

- README.md
- changelogs/fragments/197-droplet-invalid-region.yaml
- changelogs/fragments/199-update-droplet-docs-examples.yaml
- plugins/modules/digital_ocean_droplet.py
- tests/integration/targets/digital_ocean_droplet/tasks/main.yml
> Updating Droplet docs and examples

- changelogs/fragments/211-droplet-data-key.yaml
- plugins/modules/digital_ocean_droplet.py
- tests/integration/targets/digital_ocean_droplet/tasks/main.yml
> Add droplet data to 'droplet' key

- .github/workflows/ansible-test-integration.yml
- .github/workflows/pull-request-integration.yml
- README.md
- plugins/modules/digital_ocean_spaces.py
- plugins/modules/digital_ocean_spaces_info.py
- tests/integration/integration_config.yml.template
- tests/integration/requirements.txt
- tests/integration/targets/digital_ocean_spaces/defaults/main.yml
- tests/integration/targets/digital_ocean_spaces/tasks/main.yml
- tests/integration/targets/digital_ocean_spaces_info/tasks/main.yml
Fixes #215.
* digital_ocean_spaces_info
* digital_ocean_spaces
```paste below
TASK [List Spaces in nyc3] ***************************************************************************
ok: [localhost] => changed=false 
data:
spaces:
- endpoint_url: https://nyc3.digitaloceanspaces.com
name: gh-ci-space
region: nyc3
space_url: https://gh-ci-space.nyc3.digitaloceanspaces.com
TASK [List Spaces in sfo3] ***************************************************************************
ok: [localhost] => changed=false 
data:
spaces: []
TASK [Create a Space in nyc3] ************************************************************************
changed: [localhost] => changed=true 
data:
space:
endpoint_url: https://nyc3.digitaloceanspaces.com
name: gh-ci-space-1
region: nyc3
space_url: …
```
> Adding spaces and spaces_info modules

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/211-droplet-data-key.yaml
- galaxy.yml
Creating release 1.15.0; small bugfix (Droplet) and new modules (Spaces).
> Release 1.15.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/219-droplet-firewall-changed-reporting.yaml
- changelogs/fragments/223-fix-digitalocean-api-documentation-links.yaml
- galaxy.yml
Creating 1.15.1; fixes Droplet idempotence (with firewall), updating DigitalOcean API documentation links, adding new contributors.
> Creating 1.15.1

- changelogs/fragments/226-ipv6-apex-domain-records.yml
- plugins/modules/digital_ocean_domain.py
- tests/integration/targets/digital_ocean_domain/tasks/main.yml
Fixes #226; I'm going to tackle individual DNS records with a new module, `digital_ocean_domain_record` (it'll be cleaner this way).
* digital_ocean_domain
> AAAA record support for digital_ocean_domain

- .github/workflows/ansible-test-integration.yml
- .github/workflows/ansible-test-sanity.yml
- .github/workflows/ansible-test-unit.yml
- .github/workflows/black.yml
- .github/workflows/pull-request-integration.yml
- changelogs/fragments/228-integration-test-timeouts.yml
> Adding timeouts to all GitHub workflows

- README.md
- plugins/modules/digital_ocean_domain_record_info.py
- tests/integration/targets/digital_ocean_domain_record_info/defaults/main.yml
- tests/integration/targets/digital_ocean_domain_record_info/tasks/main.yml
Fixes #230.
* digital_ocean_domain_record_info
> Adding digital_ocean_domain_record_info

- changelogs/fragments/232-kubernetes-documentation-elements.yml
- plugins/modules/digital_ocean_kubernetes.py
Fixes #232.
* digital_ocean_kubernetes
> Kubernetes sanity tests failing on devel

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/226-ipv6-apex-domain-records.yml
- changelogs/fragments/228-integration-test-timeouts.yml
- changelogs/fragments/232-kubernetes-documentation-elements.yml
- galaxy.yml
Release 1.6.0; bugfixes (`digital_ocean_kubernetes`), minor changes (`digital_ocean_domain` and GH actions), and a new module (`digital_ocean_domain_record_info`).
> Release 1.16.0

- changelogs/fragments/237-parameterize-do-api-baseurl.yaml
- plugins/doc_fragments/digital_ocean.py
- plugins/module_utils/digital_ocean.py
- plugins/modules/digital_ocean_block_storage.py
- plugins/modules/digital_ocean_cdn_endpoints.py
- plugins/modules/digital_ocean_cdn_endpoints_info.py
- plugins/modules/digital_ocean_database.py
- plugins/modules/digital_ocean_database_info.py
- plugins/modules/digital_ocean_firewall.py
- plugins/modules/digital_ocean_sshkey.py
Parameterize (and default) the DigitalOcean API base URL; fixes #237.
* `digital_ocean`
> Parameterize the DigitalOcean API base URL

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/237-parameterize-do-api-baseurl.yaml
- galaxy.yml
Release 1.17.0; minor change (allow overriding the DigitalOcean API url).
> Release 1.17.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/248-oauth-token-consistency.yaml
- changelogs/fragments/251-cdn-endpoints-examples-wrong-module.yaml
- changelogs/fragments/252-cdn-endpoints-http-500.yaml
- galaxy.yml
Minor Changes
-------------
- digital_ocean - reference C(DO_API_TOKEN) consistently in module documentation and examples (https://github.com/ansible-collections/community.digitalocean/issues/248).
Bugfixes
--------
- digital_ocean_cdn_endpoints - remove non-API parameters before posting to the API (https://github.com/ansible-collections/community.digitalocean/issues/252).
- digital_ocean_cdn_endpoints - use the correct module name in the C(EXAMPLES) (https://github.com/ansible-collections/community.digitalocean/issues/251).
> Release 1.19.0

- README.md
Update supported and required versions in the readme
- Mention ansible-core and python versions
- Move the block under installation
readme
> Update supported and required versions in the readme

- .github/workflows/pull-request-integration.yml
- changelogs/fragments/259-integration-testing-by-module.yaml
Only run the integration tests on the changed module_utils or modules.
> CI: Only test changed module_utils or modules

- .github/workflows/pull-request-integration.yml
- changelogs/fragments/259-integration-testing-by-module.yaml
This reverts commit 8967360db8051f0e55f8feadc913e173644c7a3a.
This didn't work at all, and, solving it while there are open PRs isn't great.
> Revert "CI: Only test changed module_utils or modules (#259)"

- CHANGELOG.rst
- changelogs/261-fix_deleting_by_id_only.yaml
- changelogs/changelog.yaml
- changelogs/fragments/258-load-balancer-with-tag.yml
- changelogs/fragments/265-get_updated_droplet_info_on_create_wait_by_id.yaml
- changelogs/fragments/267-update-cdn-endpoints.yaml
- galaxy.yml
Release 1.120; minor changes (`digital_ocean_cdn_endpoints` and `digital_ocean_load_balancer`) and bugfixes (`digital_ocean_droplet`).
> Release 1.20.0

- README.md
- changelogs/fragments/268-update-dev-test-setup.yaml
> Refresh the "Testing and Development" section of `README.md`

- .github/workflows/pull-request-integration.yml
- changelogs/fragments/293-integration-test-pr-environment.yaml
Add missing `environment` directive on pull request integration tests; relates to #293.
- integration tests
> Add missing `environment` directive on pull request integration tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/268-update-dev-test-setup.yaml
- changelogs/fragments/270-load-balancer-size-unit.yaml
- changelogs/fragments/289-database-info-integration-test.yml
- changelogs/fragments/291-pr-integration-tests-branch.yaml
- changelogs/fragments/293-integration-test-pr-environment.yaml
- galaxy.yml
Release 1.23.0; minor changes and bugfixes.
> Release 1.23.0

- .github/workflows/ansible-test-integration.yml
- changelogs/fragments/312-double-integration-test-timeout.yaml
Double the integration test timeout.
> Double the integration test timeout

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/314-add-cname-example-to-domain_record-module.yaml
- changelogs/fragments/316-inventory-plugin-restore-reading-auth-token-from-env-variables.yaml
- changelogs/fragments/323-project-resource-info-module.yaml
- galaxy.yml
Minor Changes
-------------
- fix sanity tests (https://github.com/ansible-collections/community.digitalocean/issues/323).
Bugfixes
--------
- inventory plugin - restore reading auth token from env variables (https://github.com/ansible-collections/community.digitalocean/pull/315).
New Modules
-----------
- digital_ocean_project_resource_info - Gather information about DigitalOcean Project Resources
> Release v1.25.0

- changelogs/fragments/334-droplet-ci-images.yml
- tests/integration/targets/digital_ocean_droplet/defaults/main.yml
- tests/integration/targets/digital_ocean_droplet/tasks/main.yml
- tests/integration/targets/digital_ocean_floating_ip/defaults/main.yml
- tests/integration/targets/digital_ocean_load_balancer/defaults/main.yml
- tests/integration/targets/digital_ocean_monitoring_alerts/defaults/main.yml
- tests/integration/targets/digital_ocean_snapshot/defaults/main.yml
> Switch Droplet CI images to Jammy

- .github/workflows/ansible-test-integration.yml
- .github/workflows/pull-request-integration.yml
- changelogs/fragments/337-refactor-integration-tests.yml
Refactor PR integration tests. Switch to `pull_request_target` and matrix across modules.
> Refactor integration test workflows

- .github/workflows/pull-request-integration.yml
- changelogs/fragments/339-refactor-integration-tests.yml
Add an approval step and gate on it.
> Refactor PR integration test workflow

- .github/workflows/pull-request-integration.yml
- changelogs/fragments/340-fix-refactor-integration-tests.yml
Can't sleep forever (vacation brain).
> Fix refactor PR integration test workflow

- README.md
> Add Ansible forum tag

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-readme.yml
- changelogs/fragments/342-collection-requirements.yml
- changelogs/fragments/347-ansible-test-python-requires.yml
- changelogs/fragments/351-ansible-core-versions.yml
- galaxy.yml
CI, documentation, and Python updates; fixes #384.
> Release 1.27.0
