ansible-collections/community.digitalocean

.github/workflows/ansible-test.yml
Currently some sanity tests are not run at all, because the Python version is fixed to 3.6.
CI
=> Run all sanity tests

plugins/modules/digital_ocean.py, plugins/modules/digital_ocean_droplet.py
Currently CI is broken, since the sanity tests fail (https://github.com/ansible-collections/overview/issues/45#issuecomment-797617217).
Fortunately these are only false-positives in this collection. This PR marks them as such.
digital_ocean
=> Fix CI by marking false-positives with no_log=False

CHANGELOG.rst, changelogs/changelog.yaml
This should make `ansible-changelog release` happier, once version `1.1.0` is ready.
=> Revert CHANGELOG.rst changes from #41

changelogs/fragments/49-fix-lb-and-cert-info.yaml, plugins/modules/digital_ocean_certificate_info.py, plugins/modules/digital_ocean_load_balancer_info.py
Fix for https://github.com/ansible-collections/community.digitalocean/issues/35 The failure reported there happens because the base URL is incorrect. It contains a trailing `?`. When building a URL for retrieving a single load balancer, it creates a malformated URL, e.g. `https://api.digitalocean.com/v2/load_balancers?/e3eb82b5-2766-42f3-a74c-d20a0fbb881c`. The API interprets the ID as a query parameter and returns a list of `load_balancers` rather than the single `load_balancer`. Hence the KeyError.
`digital_ocean_certificate_info` suffers from the same issue.
- load_balancer_info
- digital_ocean_certificate_info
Test case:
```paste below
---
- hosts: localhost
connection: local
vars:
do_load_balancer_id: ""
do_certificate_id: ""
oauth_token: "{{ lookup('env', …
```
=> load_balancer_info, certificate_info: Fix base URL

changelogs/fragments/44-fixes-inv-script-host-option.yaml, scripts/inventory/digital_ocean.py
Two minor fixes related to the `--host` option to the inventory script:
1. Currently if a non integer value is passed the script throws this back at you:
```
python ./hosts/digital_ocean.py --host abc
Traceback (most recent call last):
File "./hosts/digital_ocean.py", line 541, in <module>
DigitalOceanInventory()
File "./hosts/digital_ocean.py", line 293, in __init__
json_data = self.load_droplet_variables_for_host()
File "./hosts/digital_ocean.py", line 484, in load_droplet_variables_for_host
host = int(self.args.host)
ValueError: invalid literal for int() with base 10: 'abc'
```
This PR fixes this by declaring that the `--host` arg should be an int in `parseargs`, which makes it a bit clearer what the HOST arg is actually supposed to be:
```
python ./hosts/digital_ocean.py --host abc …
```
=> Fixes rel inventory script --host option: don't throw ValueError on invalid droplet ID, return JSON conformant with specification.

changelogs/fragments/45-fix-use_private_network.yaml, scripts/inventory/digital_ocean.py
`use_private_network` is documented as a inventory script INI config option. This options is present in code but it's not hooked up to anything. This PR hooks it up in a manner consistent with the description of how it should work that exist in code:
> Use the private network IP address instead of the public when available.
In addition, code docs states `do_ip_address` and `do_private_ip_address` variables are registered by the inventory script. However, they weren't. This PR registers these fields as they are used in implementing `use_private_network`.
scripts/inventory/digital_ocean.py
```paste below
```
=> Implement documented but unimplemented `use_private_network` INI config option.

changelogs/fragments/46-fix-domain-create-return-records.yaml, plugins/modules/digital_ocean_domain.py
Return zone records even if creating a new domain, fixes #46 .
* digital_ocean_domain
Here's the behavior in this branch:
```paste below
❯ doctl compute domain delete digitalocean.letsbuildthe.cloud -f
<deleted the domain>
❯ ansible-playbook -i localhost, -c local dns.yml -v
PLAY [localhost] **********************************************************************************************************************************************************
TASK [Create a domain] ****************************************************************************************************************************************************
Sunday 11 April 2021  10:23:22 -0400 (0:00:00.053)       0:00:00.053 **********
changed: [localhost] => changed=true
ansible_facts: …
```
=> Return zone records when creating domain

README.md, changelogs/fragments/81-fix-document-link-digital-ocean-droplet-info.yml
I've just noticed the incorrect documentation link for `digital_ocean_droplet_info` while I'm comparing the documentations from ansible galaxy site to this repository.
=> Fix documentation link for `digital_ocean_droplet_info`

changelogs/fragments/83-droplet-inactive.yaml, plugins/modules/digital_ocean_droplet.py, tests/integration/targets/digital_ocean_droplet/tasks/main.yml
Droplet creation for `state: inactive` was broken (Droplet was `active`); added integration tests to verify. Fixed #83 and #66.
* `digital_ocean_droplet`
=> Issues 83 and 66

changelogs/fragments/88-droplet-integration-tests.yaml, plugins/modules/digital_ocean_droplet.py, tests/integration/targets/digital_ocean_droplet/tasks/main.yml
Fix Droplet integration tests
* `digital_ocean_droplet`
=> Fix Droplet integration tests

changelogs/fragments/68-fix-sshkey-traceback.yaml, plugins/modules/digital_ocean_sshkey.py
This resolves an issue that reports a traceback instead of a useful error message when providing an invalid `ssh_public_key` while using the `digital_ocean_sshkey` module. This stemmed from the way that the code was attempting to parse the provided key. There may be a better way to determine if a string is a public key that we can refine in the future, but for now this PR just captures the error and let's the user know what needs to be investigated.
Fixes #68 
digital_ocean_sshkey
N/A
=> Fix ssh traceback issue (#68)

changelogs/fragments/92-snapshot-info-fix-get-by-id.yaml, plugins/modules/digital_ocean_snapshot_info.py, tests/integration/targets/digital_ocean_snapshot_info/tasks/main.yml
This PR fixes the functionality of the `digital_ocean_snapshot_info` to be able to lookup a snapshot with `snapshot_type: "by_id"`
Fixes #92 
`digital_ocean_snapshot_info`
The current implementation fails because it is looking for the wrong key (`snapshot` vs. `snapshots`). Once this was resolved, it was then necessary to change some of the `base_url` logic due to when a lookup by id didn't match a valid id, it returned everything instead of returning the expected error.
Integration tests have been added to test out the expected functionality.
```paste below
```
=> Fix snapshot_info module 

changelogs/fragments/98-api-token-command.yml, plugins/inventory/digitalocean.py, tests/unit/plugins/inventory/test_digitalocean.py
This PR adds support for templates in the API token field. This mechanism allows retrieving the password from arbitrary sources (for example, a password manager).
Example script `get-do-token.sh` that just writes the API token to stdout:
```sh
#!/usr/bin/env sh
echo 'your-api-token-here'
```
Inventory config `inventory_digitalocean.yml`, referencing the script:
```yml
plugin: community.digitalocean.digitalocean
api_token: '{{ lookup("pipe", "./get-do-token.sh") }}'
```
=> Support templating of the API token

changelogs/fragments/97-wire-up-inventory-cache.yml, plugins/inventory/digitalocean.py, tests/unit/plugins/inventory/test_digitalocean.py
The inventory plugin advertises support for caching, but the implementation was missing the required pieces to make it work properly.
This commit split the inventory construction into two stages. The first stage is responsible for fetching remote data (interacting with the DigitalOcean's API). The second stage extracts the relevant data from the API responses and populated the inventory.
Caching support then came almost for free. All we had to do is only fetch data if:
1. User does not want to use cache at all.
2. User does use cache and wants data refreshed.
3. User does use cache, but the cache is empty.
Some additional logic makes sure we write the data to cache if data refresh is requested, but nothing too complex.
`community.digitalocean.digitalocean` inventory …
=> Actually activate inventory caching

changelogs/fragments/102-filters-prefixed-vars.yml, plugins/inventory/digitalocean.py, tests/unit/plugins/inventory/test_digitalocean.py
This PR is mutually exclusive with #103 .
In contrast to the jinja expressions in `compose`, `groups` and `keyed_groups`, `filters` was given *all* droplet attributes without a prefix. My bad for not catching that.
Note that this will break anyone who started using this feature since the release of version 1.5.0. If that is a no-go, I can amend the PR to keep the previous inconsistent behavior as well.
Before:
```yml
plugin: community.digitalocean.digitalocean
attributes:
- tags
filters:
- '"test" in tags'
```
or even without the attributes:
```yml
plugin: community.digitalocean.digitalocean
filters:
- '"test" in tags'
```
After:
```yml
plugin: community.digitalocean.digitalocean
attributes:
- tags
filters:
- '"test" in do_tags'
```
=> Pass only prefixed attributes to filters

changelogs/fragments/116-droplet-present-wait.yaml, plugins/modules/digital_ocean_droplet.py
State `present` with `wait` should wait for power on; fixes #116.
=> Fix Droplet present state (with wait)

changelogs/fragments/138-group-name-transformations.yaml, plugins/inventory/digitalocean.py, tests/unit/plugins/inventory/test_digitalocean.py
Up until now, the inventory plugin always replaced invalid characters in group names, which can be a bit surprising when we generate groups on things such as droplet tags. To make things even more confusing, the TRANSFORM_INVALID_GROUP_CHARS configuration option is completely ignored, giving users no way of preserving original names.
This commit replaces the default group name sanitization function with the one that respects the TRANSFORM_INVALID_GROUP_CHARS configuration option.
Fixes #133 
=> Respect the TRANSFORM_INVALID_GROUP_CHARS setting

changelogs/fragments/157-doks-auto-scale.yaml, plugins/modules/digital_ocean_kubernetes.py
Fixes #157.
* digital_ocean_kubernetes
Seems to work just fine:
```paste below
❯ doctl kubernetes cluster get 70098f48-d3fb-41db-9aa3-3181d61e2cb1 -o json | jq -r '.[0].node_pools'
[
{
"id": "de2a8eb3-740a-4a0e-9ab6-0b0ad11173e0",
"name": "hacktoberfest-workers",
"size": "s-1vcpu-2gb",
"count": 1,
"tags": [
"k8s",
"k8s:70098f48-d3fb-41db-9aa3-3181d61e2cb1",
"k8s:worker"
],
"auto_scale": true,
"min_nodes": 1,
"max_nodes": 3,
"nodes": [
{
"id": "528ee3e6-ef68-44f1-9864-c0d50edae628",
"name": "hacktoberfest-workers-81yxu",
"status": {
"state": "running"
},
"droplet_id": "263706237",
"created_at": "2021-09-07T23:37:27Z",
"updated_at": "2021-09-07T23:41:41Z"
}
]
}
]
```
I used this play:
```ansible
- name: Create a new DigitalOcean Kubernetes cluster in New York 1 …
```
=> Adding taints, autoscale, min_nodes and max_nodes to node_pools

changelogs/fragments/150-droplet-active-power-on.yaml, plugins/modules/digital_ocean_droplet.py
Might be related to #150. In any event, ensuring "active" (versus "new") seems like a good idea before triggering the "power on" action.
=> Ensure active before power on

changelogs/fragments/162-floating-ip-data-idempotency.yaml, plugins/modules/digital_ocean_floating_ip.py
Floating IP module is idempotent when a Droplet ID is provided. However, the returned data structure is different between the run when the IP is created and the run it is already present. This pull-request fixes the returned data for the state that the floating IP is present. Please see the output below.
`community.digitalocean.digital_ocean_floating_ip`
The test:
```yaml
- name: Create floating IP address
community.digitalocean.digital_ocean_floating_ip:
state: present
droplet_id: "123456"
register: floating_ip
- debug:
var: floating_ip
```
Output when floating IP is created:
```
TASK [Create floating IP address] **********************************************
changed: [localhost]
TASK [debug] *******************************************************************
ok: …
```
=> Fix returned data for already present floating IP

README.md, changelogs/fragments/163-documentation-broken-links.yaml
Documentation links are broken for digital_ocean_domain_record and digital_ocean_droplet_info modules. This is the fix.
`digital_ocean_domain_record` and `digital_ocean_droplet_info`
=> Fix documentation links for digital_ocean_domain_record and digital_ocean_droplet_info

.github/workflows/ansible-test-integration.yml, changelogs/fragments/165-serialize-integration-tests.yml
It looks like we're probably running into race conditions with concurrent integration test runs. It's probably a better idea to serialize them, regardless.
The integration tests.
=> Serialize the integration tests

changelogs/fragments/171-add-project-support.yaml, plugins/module_utils/digital_ocean.py, plugins/modules/digital_ocean_block_storage.py, plugins/modules/digital_ocean_database.py, plugins/modules/digital_ocean_domain.py, plugins/modules/digital_ocean_droplet.py, plugins/modules/digital_ocean_floating_ip.py, plugins/modules/digital_ocean_load_balancer.py, tests/integration/targets/digital_ocean_block_storage/defaults/main.yml, tests/integration/targets/digital_ocean_block_storage/tasks/main.yml, tests/integration/targets/digital_ocean_database/defaults/main.yml, tests/integration/targets/digital_ocean_database/tasks/main.yml, tests/integration/targets/digital_ocean_domain/defaults/main.yml, tests/integration/targets/digital_ocean_domain/tasks/main.yml, tests/integration/targets/digital_ocean_droplet/defaults/main.yml, tests/integration/targets/digital_ocean_droplet/tasks/main.yml, tests/integration/targets/digital_ocean_floating_ip/defaults/main.yml, tests/integration/targets/digital_ocean_floating_ip/tasks/main.yml, tests/integration/targets/digital_ocean_load_balancer/defaults/main.yml, tests/integration/targets/digital_ocean_load_balancer/tasks/main.yml
Fixes #171.
Adds Project assignment support (at the time of creation) for the following modules:
* digital_ocean_block_storage
* digital_ocean_database
* digital_ocean_domain
* digital_ocean_floating_ip
* digital_ocean_load_balancer
That is, the ability to associate these resources to [Projects](https://docs.digitalocean.com/products/projects/) when they're created.
Trying to make the smallest possible change, so, if the project isn't specified, the behavior will be unchanged (i.e., the resources will land in the "default" Project as before).
=> Adding Project support

changelogs/fragments/174-return-value-fix.yml, plugins/modules/digital_ocean_kubernetes.py
SUMMARY
The return values for the digital_ocean_kubernetes module are made consistent with what is documented. This change removes the extra "kubernetes_cluster" key that was present only when creating a new resource (changes were already consistent). Also adds the same return values when a resource is deleted so you can still use those values dynamically for further tasks.
Fixes #174 but only for the digital_ocean_kubernetes module.
ISSUE TYPE
COMPONENT NAME
digital_ocean_kubernetes
=> Fix return values for digital_ocean_kubernetes module (#174)

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/199-update-droplet-docs-examples.yaml, changelogs/fragments/201-droplet-unique-name.yaml, changelogs/fragments/204-kubernetes-tags-and-info.yaml, changelogs/fragments/205-cdn-endpoints.yaml, galaxy.yml
Release 1.14.0; minor changes to `digital_ocean_kubernetes_info` and bugfixes for `digital_ocean_cdn_endpoints` and `digital_ocean_droplet`.
=> Release 1.14.0

changelogs/fragments/219-droplet-firewall-changed-reporting.yaml, plugins/modules/digital_ocean_droplet.py, tests/integration/targets/digital_ocean_droplet/tasks/main.yml
When using the droplet module, the presence of the `firewall` argument causes the module to always report changed=True, even when no changes were necessary/made. This patch causes it to track if the droplet needed to be added or removed from any firewalls and reports changed appropriately. 
Running the droplet module even with an empty list passed to firewalls returns changed=true.
```
- name: Show a droplet always changing just because firewall is present
community.digitalocean.digital_ocean_droplet:
state: present
oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
id: 123
name: mydroplet
size: s-1vcpu-1gb
region: sfo3
image: ubuntu-20-04-x64
firewall: []
wait_timeout: 500
```
=> make droplet firewall adding/removing report changed properly

changelogs/fragments/243-no-log-spaces-access-key-id.yaml, plugins/modules/digital_ocean_spaces.py, plugins/modules/digital_ocean_spaces_info.py
Fixes #243.
* `digital_ocean_spaces`
* `digital_ocean_spaces_info`
=> Set no_log=True for aws_access_key_id parameter

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/239-ci-stable-2.13.yaml, changelogs/fragments/243-no-log-spaces-access-key-id.yaml, galaxy.yml
Release 1.18.0; adding `stable-2.13` to CI for sanity and unit testing and adding`no_log=True` to `aws_access_key_id` in the Spaces modules.
=> Creating 1.18.0

changelogs/fragments/248-oauth-token-consistency.yaml, changelogs/fragments/251-cdn-endpoints-examples-wrong-module.yaml, changelogs/fragments/252-cdn-endpoints-http-500.yaml, plugins/modules/digital_ocean.py, plugins/modules/digital_ocean_block_storage.py, plugins/modules/digital_ocean_cdn_endpoints.py, plugins/modules/digital_ocean_domain_record.py, plugins/modules/digital_ocean_domain_record_info.py, plugins/modules/digital_ocean_kubernetes.py, plugins/modules/digital_ocean_load_balancer.py, tests/integration/targets/digital_ocean_cdn_endpoints/defaults/main.yml
Remove non-DO API parameters before POSTing the create to the API and use the correct module name in the `EXAMPLES`. Consistently reference `$DO_API_TOKEN` in the `DOCUMENTATION` and `EXAMPLES`. Switch from `time.time()` to `time.monotonic()` as it seems like some of the integration tests were being affected by clock skew; also, simplify the polling interval -- we can spare a few seconds to look at `time.sleep(10)` versus `time.sleep(min(10, end_time - time.monotonic()))`.
Fixes #251 and #252 and #248.
* `digital_ocean`
* `digital_ocean_block_storage`
* `digital_ocean_cdn_endpoints`
* `digital_ocean_domain_record`
* `digital_ocean_domain_record_info`
=> Remove non-API params; fix DOCUMENTATION and EXAMPLES; consistently reference $DO_API_TOKEN

changelogs/261-fix_deleting_by_id_only.yaml, plugins/modules/digital_ocean_droplet.py, tests/integration/targets/digital_ocean_droplet/tasks/main.yml
For droplet deletion, #184 required `name` and `unique_name` and
verified `unique_name` is true, to the exclusion of `id`.
Remove requirement from `required_if` as it cannot enforce the logic
`id or (name and unique_name)` and modify the verification of
`unique_name` to include `id` (and don't worry about `name` because
either it or `id` are already required elsewhere).
Fixes #260.
=> Allow deleting droplet by id

changelogs/fragments/258-load-balancer-with-tag.yml, plugins/modules/digital_ocean_load_balancer.py, tests/integration/targets/digital_ocean_load_balancer/defaults/main.yml, tests/integration/targets/digital_ocean_load_balancer/tasks/main.yml
Adding the ability to create a load balancer with a tag. Currently load balancers can only be created with a list of droplet IDs even though the API supports tags.
digital_ocean_load_balancer
N/A
=> Added support for creating a load balancer with a tag

changelogs/fragments/265-get_updated_droplet_info_on_create_wait_by_id.yaml, plugins/modules/digital_ocean_droplet.py, tests/integration/targets/digital_ocean_droplet/tasks/main.yml
When updating droplet info while waiting after creation, instead of
using `get_droplet()` and being dependent upon the optional
`unique_name` feature, use `get_by_id()` with the droplet's ID which
we should have having just created the droplet.
Fixes #220.
=> Get updated droplet by id during create wait

changelogs/fragments/273-Dont_call_get_on_None.yaml, plugins/modules/digital_ocean_droplet.py
Instead of throwing an exception, be more defensive in the code: if
the API's JSON response lacks a key and we correspondingly set a
variable to `None`, then don't call `get()` on the variable, but test
the variable first.
AttributeError: 'NoneType' object has no attribute 'get'
Fixes #272.
```
AttributeError: 'NoneType' object has no attribute 'get'
```
=> Don't throw an exception if API's JSON response lacks an expected key

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/247-sanity-checks-2.12-13.yaml, changelogs/fragments/273-Dont_call_get_on_None.yaml, galaxy.yml
* Small bugfix to `digital_ocean_droplet`
* Add sanity test ignores for Ansible 2.12 and 2.13
=> Release 1.21.0

changelogs/fragments/276-vpc-inconsistent-data-return.yml, plugins/modules/digital_ocean_vpc.py, tests/integration/targets/digital_ocean_vpc/tasks/main.yml
Fixes #276.
`community.digitalocean.digital_ocean_vpc`
=> Add `vpc` key to returned VPC data on create

README.md, changelogs/fragments/281-default-all-action-group.yml, meta/runtime.yml
Add an action_group to default vars for every module
This allows, for example, to default the value of oauth_token once
without needing to specify it in every task unless it needs to be
overridden.
meta/runtime.yml
Inspired by azure.azcollection's recent fix: https://github.com/ansible-collections/azure/pull/874
Edit: it looks like this for the example in the README:
=> Add an action_group to default vars for every module

.github/workflows/ansible-test-integration.yml
Split the integration tests by module and run them serially. With as many modules as there are in this collection, going through the output when integration tests fail has become too daunting. [Here's](https://github.com/ansible-collections/community.digitalocean/actions/runs/3119044015) an example of how this will behave.
* integration tests
=> Split integration testing by module

.github/workflows/ansible-test-integration.yml, .github/workflows/pull-request-integration.yml, changelogs/fragments/286-refactor-pr-integration-testing.yaml
Fixed #286. Currently, integration testing on pull requests runs the entire battery of integration tests. While thorough, it's not necessary. In the case where module_utils change, run all of the integration tests. In the case where modules are changed, just run the integration tests for those modules.
- CI enhancement
- Integration tests
=> Split integration testing by module (on pull request)

.github/workflows/pull-request-integration.yml, CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/276-vpc-inconsistent-data-return.yml, changelogs/fragments/281-default-all-action-group.yml, changelogs/fragments/286-refactor-pr-integration-testing.yaml, galaxy.yml
Release 1.22.0; minor changes in the collection: adding action group `community.digitalocean.all` and adding `vpc` key to data returned in `digital_ocean_vpc`. Refactoring integration testing so that the daily runs are split by module and integration test pull requests either happen for all modules (for changes under `module_utils`) or on the affected modules (for changes under `modules`).
=> Release 1.22.0

changelogs/fragments/289-database-info-integration-test.yml, tests/integration/targets/digital_ocean_database_info/tasks/main.yml
Add integration test for `digital_ocean_database_info`; fixes #289.
- Integration tests
=> Add integration test for `digital_ocean_database_info`

.github/workflows/pull-request-integration.yml, changelogs/fragments/291-pr-integration-tests-branch.yaml
Point pull request integration tests as the pull request branch (not the most recent commit); fixes #291.
- Integration tests
=> Point PR integration tests at PR branch

changelogs/fragments/270-load-balancer-size-unit.yaml, plugins/doc_fragments/digital_ocean.py, plugins/modules/digital_ocean_load_balancer.py, tests/integration/targets/digital_ocean_load_balancer/tasks/main.yml
Add support for `size_unit` (versus `size`); deprecate `algorithm` -- fixes #270.
This field has been replaced by the `size_unit` field for all regions except in AMS2, NYC2, and SFO1.
The formula is lb-small = 1 node, lb-medium = 3 nodes, lb-large = 6 nodes.
- `digital_ocean_load_balancer`
=> Update `digital_ocean_load_balancer` (for `size_unit`)

plugins/inventory/digitalocean.py
Allows baseurl parameter in the inventory plugin to be changed from the default.
=> Bugfix for baseurl parameter in inventory plugin

.github/workflows/ansible-test-sanity.yml, .github/workflows/ansible-test-unit.yml, .github/workflows/black.yml, changelogs/fragments/311-update-tests.yaml
Accidentally took these tests off of `main` in the last pull request.
=> Add tests back on main

changelogs/fragments/300-inventory-plugin-oauth-token.yaml, plugins/inventory/digitalocean.py, poetry.lock, pyproject.toml, tests/unit/plugins/inventory/test_digitalocean.py
Fixes #300; drop `api_token` in favor of `oauth_token`.
- `digitalocean` inventory plugin
```paste below
N/A
```
=> Inventory plugin: drop `api_token` in favor of `oauth_token`

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/300-inventory-plugin-oauth-token.yaml, changelogs/fragments/303-documentation-bool-true-false.yaml, changelogs/fragments/307-get-all-domains-pagination-fix.yaml, changelogs/fragments/310-update-tests.yaml, changelogs/fragments/311-update-tests.yaml, changelogs/fragments/312-double-integration-test-timeout.yaml, galaxy.yml
Minor Changes
-------------
- documentation - use C(true) and C(false) for boolean values in documentation and examples (https://github.com/ansible-collections/community.digitalocean/issues/303).
- inventory plugin - drop C(api_token) in favor of C(oauth_token) for consistency (https://github.com/ansible-collections/community.digitalocean/issues/300).
- tests - add C(sanity), C(units), and C(psf/black) back on merge into C(main) (https://github.com/ansible-collections/community.digitalocean/pull/311).
- tests - drop Ansible 2.9 and Ansible Core 2.10 and 2.11 (https://github.com/ansible-collections/community.digitalocean/pull/310).
- tests - remove the daily runs (https://github.com/ansible-collections/community.digitalocean/pull/310).
- tests - run C(psf/black) across all files …
=> Release 1.24.0

changelogs/fragments/314-add-cname-example-to-domain_record-module.yaml, plugins/modules/digital_ocean_domain_record.py
Here I added an example for the CNAME type of the domain_record module.
I believe subdomains to be a particularly common usage of this record type.
I added the subdomains I use.
digital_ocean_domain_record.py
When setting up my cname records it wasn't apparent what to put into the data, domain, or name fields, leading to a cryptic error on CNAMEs not being allowed to refer to themselves.
=> add CNAME example to domain_record module

changelogs/fragments/316-inventory-plugin-restore-reading-auth-token-from-env-variables.yaml, plugins/doc_fragments/digital_ocean.py
By completely removing any documentation for api_token / oauth_token, commit 609df3eaf506a5db13a960d5fc4bf4f70b5a3e50 suddenly broke support for reading the auth token from environment variables (which magically happens to work based on plugin options documentation).
Restore the documentation bits by matching docs fragment. While at it, also match the documented list of supported env variables which can be used as auth token sources.
Fixes #315
=> Inventory plugin: restore reading auth token from env variables

.gitignore, changelogs/fragments/323-project-resource-info-module.yaml, plugins/doc_fragments/digital_ocean.py, plugins/module_utils/digital_ocean.py, plugins/modules/digital_ocean.py, plugins/modules/digital_ocean_cdn_endpoints.py, plugins/modules/digital_ocean_cdn_endpoints_info.py, plugins/modules/digital_ocean_database.py, plugins/modules/digital_ocean_database_info.py, plugins/modules/digital_ocean_domain_record.py, plugins/modules/digital_ocean_domain_record_info.py, plugins/modules/digital_ocean_droplet.py, plugins/modules/digital_ocean_droplet_info.py, plugins/modules/digital_ocean_firewall.py, plugins/modules/digital_ocean_kubernetes.py, plugins/modules/digital_ocean_kubernetes_info.py, plugins/modules/digital_ocean_load_balancer.py, plugins/modules/digital_ocean_monitoring_alerts.py, plugins/modules/digital_ocean_monitoring_alerts_info.py, plugins/modules/digital_ocean_project.py, plugins/modules/digital_ocean_project_info.py, plugins/modules/digital_ocean_project_resource_info.py, plugins/modules/digital_ocean_snapshot.py, plugins/modules/digital_ocean_sshkey.py, plugins/modules/digital_ocean_vpc.py, plugins/modules/digital_ocean_vpc_info.py, tests/integration/targets/digital_ocean_project_resource_info/defaults/main.yml, tests/integration/targets/digital_ocean_project_resource_info/tasks/main.yml, tests/unit/plugins/inventory/test_digitalocean.py
Fixes #323 
project resource info module
=> Add project resource info module

changelogs/fragments/322-k8s-module-kubeconfig.yaml, plugins/modules/digital_ocean_kubernetes.py, tests/integration/targets/digital_ocean_kubernetes/tasks/main.yml
Fixes #322 
digital_ocean_kubernetes module
=> Fix unexpected return data bug in the kubernetes module

.github/workflows/ansible-test-integration.yml, .github/workflows/pull-request-integration.yml, changelogs/fragments/338-refactor-integration-tests.yml, tests/integration/integration_config.yml.template, tests/integration/targets/digital_ocean_block_storage/defaults/main.yml, tests/integration/targets/digital_ocean_cdn_endpoints/aliases, tests/integration/targets/digital_ocean_domain_record_info/aliases, tests/integration/targets/digital_ocean_droplet/defaults/main.yml, tests/integration/targets/digital_ocean_floating_ip/defaults/main.yml, tests/integration/targets/digital_ocean_kubernetes/defaults/main.yml, tests/integration/targets/digital_ocean_kubernetes_info/defaults/main.yml, tests/integration/targets/digital_ocean_kubernetes_info/tasks/main.yml, tests/integration/targets/digital_ocean_load_balancer/defaults/main.yml, tests/integration/targets/digital_ocean_monitoring_alerts/aliases, tests/integration/targets/digital_ocean_monitoring_alerts/defaults/main.yml, tests/integration/targets/digital_ocean_project_resource_info/aliases, tests/integration/targets/digital_ocean_snapshot/defaults/main.yml
Comment out non-existent tests and lower parallelism.
=> Iterate refactor integration tests

changelogs/fragments/326-project-name-param.yaml, plugins/modules/digital_ocean_block_storage.py, plugins/modules/digital_ocean_database.py, plugins/modules/digital_ocean_domain.py, plugins/modules/digital_ocean_droplet.py, plugins/modules/digital_ocean_floating_ip.py, plugins/modules/digital_ocean_load_balancer.py
Replaced self.module.params.get("project") with self.module.params.get("project_name") 
Fixes #326
Fixes #255
digital_ocean_block_storage
digital_ocean_database
digital_ocean_domain
digital_ocean_floating_ip
digital_ocean_load_balancer
=> Fix project_name parameter

changelogs/fragments/264-kubernetes-project.yaml, plugins/module_utils/digital_ocean.py, plugins/modules/digital_ocean_kubernetes.py, tests/integration/targets/digital_ocean_kubernetes/defaults/main.yml, tests/integration/targets/digital_ocean_kubernetes/tasks/main.yml, tests/unit/plugins/modules/test_digital_ocean_kubernetes.py
Fixes #264 
digital_ocean_kubernetes
=> Add project_name parameter to the kubernetes module

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/264-kubernetes-project.yaml, changelogs/fragments/322-k8s-module-kubeconfig.yaml, changelogs/fragments/326-project-name-param.yaml, changelogs/fragments/334-droplet-ci-images.yml, changelogs/fragments/337-refactor-integration-tests.yml, changelogs/fragments/338-refactor-integration-tests.yml, changelogs/fragments/339-refactor-integration-tests.yml, changelogs/fragments/340-fix-refactor-integration-tests.yml, galaxy.yml
Minor Changes
-------------
- digital_ocean_kubernetes - add project_name parameter (https://github.com/ansible-collections/community.digitalocean/issues/264).
Bugfixes
--------
- The C(project_name) parameter for many modules was used by alias C(project) internally in the codebase, but to work properly C(project_name) must be used in the code. Replace self.module.params.get("project") with self.module.params.get("project_name") (https://github.com/ansible-collections/community.digitalocean/issues/326).
- digital_ocean_kubernetes - module didn't return kubeconfig properly, return documentation was invalid. Fixed version returns data with the same structure all the time, also it is aligned with M(community.digitalocean.digital_ocean_kubernetes_info) documentation return data now. …
=> Release v1.26.0

changelogs/fragments/347-ansible-test-python-requires.yml, tests/config.yml
=> Define `python_requires` for `ansible-test`

.github/workflows/ansible-test-sanity.yml, .github/workflows/ansible-test-unit.yml, README.md, changelogs/fragments/351-ansible-core-versions.yml, tests/utils/render.sh
Fixes #351; drop deprecated versions of `ansible-core` (2.12 and 2.13), add newer versions (2.14 and 2.15).
=> Add new and drop deprecated versions of `ansible-core`

plugins/inventory/digitalocean.py
There is a typo in the documentation examples section.
The closing parenthesis of the pipe lookup is missing, so the provided code snippet is unusable.
digitalocean inventory plugin
=> [FIX] digitalocean inventory plugin: missing closing parenthesis in examples section
